apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: argocd
  name: argocd
spec:
  ingressClassName: nginx
  rules:
  - host: argo.juwon.codes 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd
            port:
              number: 443