apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ghost
  name: argocd
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - juwon.codes
    secretName: tls-secret
  rules:
  - host: juwon.codes 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ghost
            port:
              number: 443
