apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ghost
  name: ghost
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: juwon.codes 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ghost
            port:
              number: 80
